# Use the official PostgreSQL image as the base image
FROM postgres:13

# Set the PostgreSQL database environment variables
ENV POSTGRES_USER=myuser \
    POSTGRES_PASSWORD=mypassword \
    POSTGRES_DB=mydatabase
