apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: your-rails-image:tag
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://example_user:example_password@postgresql/example_db"
